spring:
  application:
    name: api-RESTful
  datasource:
    url: jdbc:postgresql://viaduct.proxy.rlwy.net:29770/railway
    username: postgres
    password: mVRvzOjCzeKwQwAslJtvUUZTzZREijwx
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
